### ISSUE TITLE
Gem not usable without text file.

### ISSUE THREAD

**Issue by LWFlouisa** [vesselinv/glove#2]
Quantum Physics text file needs to be provided, to be able to test it out.

**Comment by watzon** [comment]
@LWFlouisa while the text file he trained with would be nice, you can train on any text. For instance I downloaded the full text for Harry Potter and the Sorcerer's Stone and trained on that. You could also download a dump from Wikipedia and train on that. Just expect it to take a very long time.

**Comment by vesselinv** [comment]
@LWFlouisa @watzon The Quantum Physics text from the readme example is located in `benchmark/data/quantum-physics.txt`. For more info on normalizations done to a given corpus see [Glove::Parses#tokenize](https://github.com/vesselinv/glove/blob/master/lib/glove/parser.rb#L40)
